<?php if (($this->getCheckout()->getStepData('shipping_method', 'complete')) && $this->isEnabledInsurance()): ?>
    <dt class="complete">
        <?php echo $this->__('Shipping Insurance') ?> <span class="changelink"><span class="separator">|</span> <a
                    href="#shipping_method"
                    onclick="checkout.changeSection('opc-shipping_method'); return false;"><?php echo $this->__('Change') ?></a></span>
    </dt>
    <dd class="complete">
        <?php if ($this->isEnabledInsurance()): ?>

            <?php echo $this->getInsuranceType() ?>
            <?php echo $this->getInsuranceRate(); ?>

        <?php endif; ?>
    </dd>
<?php endif; ?>