<input name="shipping_insurance" type="checkbox" id="s_method_insurance" class="checkbox"/>
<label for="s_method_insurance">
    <?php echo $this->__('Include Insurance');?>
</label>
<div id="cost_shipping"><?php echo $this->getShipping(); ?></div>



<script>
    <?php if (!empty($shippingCodePrice)): ?>
    var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};

    <?php endif; ?>

    // jQuery("#s_method_insurance").change(function() {
    //     var checkedMethod = jQuery('input[type="radio"][name="shipping_method"]:checked');
    //     alert( jQuery(checkedMethod).val() );
    // });


    //each(function(el){
    //    Event.observe(el, 'click', function(){
    //        alert("ss");
    //        if (el.checked === true) {
    //
    //            var getShippingCode = el.getValue();
    //            <?php //if (!empty($shippingCodePrice)): ?>
    //            var newPrice = shippingCodePrice[getShippingCode];
    //
    //            if (!lastPrice) {
    //                lastPrice = newPrice;
    //                quoteBaseGrandTotal += newPrice;
    //            }
    //            if (newPrice !== lastPrice) {
    //                quoteBaseGrandTotal += (newPrice-lastPrice);
    //                lastPrice = newPrice;
    //            }
    //            <?php //endif; ?>
    //            checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    //            return false;
    //        }
    //    });
    //});

</script>
