<?php
/**
 * Created by Magentix
 * Based on Module from "Excellence Technologies" (excellencetechnologies.in)
 *
 * @category   Magentix
 * @package    Magentix_Fee
 * @author     Matthieu Vion (http://www.magentix.fr)
 * @license    This work is free software, you can redistribute it and/or modify it
 */
?>

<?php $this->setPriceDataObject($this->getSource()) ?>

<?php if ((float) $this->getSource()->getShippinginsuranceAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('shippinginsurance')->__('Shipping Insurance') ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseShippinginsuranceAmount(), $this->getSource()->getShippinginsuranceAmount()); ?>
        </td>
    </tr>
<?php endif; ?>