<?php $this->setPriceDataObject($this->getSource()); ?>

<?php if ((float) $this->getSource()->getShippinginsuranceAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('shippinginsurance')->__('Shipping Insurance') ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseShippinginsuranceAmount(), $this->getSource()->getShippinginsuranceAmount()); ?>
        </td>
    </tr>
<?php endif; ?>